[package]
name = "unreql_deadpool"
version = "0.1.0"
edition = "2021"

[dependencies]
unreql = { path = "../reql" }
deadpool = "0.10.0"
async-trait = "0.1.79"

[dev-dependencies]
serde = { version = "1.0.192", features = ["derive"] }
