[package]
name = "unreql_deadpool"
version = "0.1.0"
edition = "2021"

[dependencies]
unreql = { version = "0.1.7", path = "../reql" }
deadpool = "0.10"
async-trait = "0.1"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
